'use strict';
const uuidv4 = require("uuid/v4");

module.exports = {
  up: (queryInterface, Sequelize) => {
    try {
      return queryInterface.bulkInsert("menus", [
        {
          id: 10000,
          uuid: uuidv4(),
          privilege_name: "User Management",
          parent_id: null,
          is_parent: 1,
          is_menu: 1,
          is_action: 0,
          action_items: "",
          sub_menu_name: "",
          api_route: "",
          frontend_route: "",
        },
        {
          id: 10100,
          uuid: uuidv4(),
          privilege_name: "Manage User",
          parent_id: 10000,
          is_parent: 0,
          is_menu: 1,
          is_action: 0,
          action_items: "",
          sub_menu_name: "",
          api_route: "",
          frontend_route: "",
        },
        {
          id: 10101,
          uuid: uuidv4(),
          privilege_name: "Create User",
          parent_id: 10000,
          is_parent: 0,
          is_menu: 0,
          is_action: 1,
          action_items: "7",
          sub_menu_name: "Manage User",
          api_route: "",
          frontend_route: "/admin/dashboard/users/register",
        },
        {
          id: 10102,
          uuid: uuidv4(),
          privilege_name: "View User",
          parent_id: 10000,
          is_parent: 0,
          is_menu: 0,
          is_action: 1,
          action_items: "1",
          sub_menu_name: "Manage User",
          api_route: "",
          frontend_route: "/admin/dashboard/users/view/:id",
        },
        {
          id: 10103,
          uuid: uuidv4(),
          privilege_name: "Edit User",
          parent_id: 10000,
          is_parent: 0,
          is_menu: 0,
          is_action: 1,
          action_items: "0",
          sub_menu_name: "Manage User",
          api_route: "",
          frontend_route: "/admin/dashboard/users/edit/:id",
        },
        {
          id: 10104,
          uuid: uuidv4(),
          privilege_name: "Block/Unblock User",
          parent_id: 10000,
          is_parent: 0,
          is_menu: 0,
          is_action: 1,
          action_items: "3",
          sub_menu_name: "Manage User",
          api_route: "",
          frontend_route: "",
        },
        {
          id: 10105,
          uuid: uuidv4(),
          privilege_name: "Reset Password User",
          parent_id: 10000,
          is_parent: 0,
          is_menu: 0,
          is_action: 1,
          action_items: "6",
          sub_menu_name: "Manage User",
          api_route: "",
          frontend_route: "",
        },
        {
          id: 20000,
          uuid: uuidv4(),
          privilege_name: "Profile Management",
          parent_id: null,
          is_parent: 1,
          is_menu: 1,
          is_action: 0,
          action_items: "",
          sub_menu_name: "",
          api_route: "",
          frontend_route: "",
        },
        {
          id: 20100,
          uuid: uuidv4(),
          privilege_name: "Manage Profile",
          parent_id: 20000,
          is_parent: 0,
          is_menu: 1,
          is_action: 0,
          action_items: "",
          sub_menu_name: "",
          api_route: "",
          frontend_route: "",
        },
        {
          id: 20101,
          uuid: uuidv4(),
          privilege_name: "Create Profile",
          parent_id: 20000,
          is_parent: 0,
          is_menu: 0,
          is_action: 1,
          action_items: "7",
          sub_menu_name: "Manage Profile",
          api_route: "",
          frontend_route: "/admin/dashboard/profile/create",
        },
        {
          id: 20102,
          uuid: uuidv4(),
          privilege_name: "View Profile",
          parent_id: 20000,
          is_parent: 0,
          is_menu: 0,
          is_action: 1,
          action_items: "1",
          sub_menu_name: "Manage Profile",
          api_route: "",
          frontend_route: "/admin/dashboard/profile/view/:id",
        },
        {
          id: 20103,
          uuid: uuidv4(),
          privilege_name: "Edit Profile",
          parent_id: 20000,
          is_parent: 0,
          is_menu: 0,
          is_action: 1,
          action_items: "0",
          sub_menu_name: "Manage Profile",
          api_route: "",
          frontend_route: "/admin/dashboard/profile/modify/:id",
        },
        {
          id: 20104,
          uuid: uuidv4(),
          privilege_name: "Block/Unblock Profile",
          parent_id: 20000,
          is_parent: 0,
          is_menu: 0,
          is_action: 1,
          action_items: "3",
          sub_menu_name: "Manage Profile",
          api_route: "",
          frontend_route: "/admin/dashboard/profile/block-unblock",
        },
        {
          id: 30000,
          uuid: uuidv4(),
          privilege_name: "Agent Management",
          parent_id: null,
          is_parent: 1,
          is_menu: 1,
          is_action: 0,
          action_items: "",
          sub_menu_name: "",
          api_route: "",
          frontend_route: "",
        },
        {
          id: 30100,
          uuid: uuidv4(),
          privilege_name: "Manage Agent",
          parent_id: 30000,
          is_parent: 0,
          is_menu: 1,
          is_action: 0,
          action_items: "",
          sub_menu_name: "",
          api_route: "",
          frontend_route: "",
        },
        {
          id: 30101,
          uuid: uuidv4(),
          privilege_name: "Create Agent",
          parent_id: 30000,
          is_parent: 0,
          is_menu: 0,
          is_action: 1,
          action_items: "7",
          sub_menu_name: "Manage Agent",
          api_route: "",
          frontend_route: "/admin/dashboard/agent/create",
        },
        {
          id: 30102,
          uuid: uuidv4(),
          privilege_name: "View Agent",
          parent_id: 30000,
          is_parent: 0,
          is_menu: 0,
          is_action: 1,
          action_items: "1",
          sub_menu_name: "Manage Agent",
          api_route: "",
          frontend_route: "/admin/dashboard/agent/view/:id",
        },
        {
          id: 30103,
          uuid: uuidv4(),
          privilege_name: "Edit Agent",
          parent_id: 30000,
          is_parent: 0,
          is_menu: 0,
          is_action: 1,
          action_items: "0",
          sub_menu_name: "Manage Agent",
          api_route: "",
          frontend_route: "/admin/dashboard/agent/modify/:id",
        },
        {
          id: 30104,
          uuid: uuidv4(),
          privilege_name: "Block/Unblock Agent",
          parent_id: 30000,
          is_parent: 0,
          is_menu: 0,
          is_action: 1,
          action_items: "3",
          sub_menu_name: "Manage Agent",
          api_route: "",
          frontend_route: "/admin/dashboard/agent/block-unblock",
        },
        {
          id: 40000,
          uuid: uuidv4(),
          privilege_name: "Training Management",
          parent_id: null,
          is_parent: 1,
          is_menu: 1,
          is_action: 0,
          action_items: "",
          sub_menu_name: "",
          api_route: "",
          frontend_route: "",
        },
        {
          id: 40100,
          uuid: uuidv4(),
          privilege_name: "Manage Training",
          parent_id: 40000,
          is_parent: 0,
          is_menu: 1,
          is_action: 0,
          action_items: "",
          sub_menu_name: "",
          api_route: "",
          frontend_route: "",
        },
        {
          id: 40101,
          uuid: uuidv4(),
          privilege_name: "Create Training",
          parent_id: 40000,
          is_parent: 0,
          is_menu: 0,
          is_action: 1,
          action_items: "7",
          sub_menu_name: "Manage Training",
          api_route: "",
          frontend_route: "/admin/dashboard/agent/create",
        },
        {
          id: 40102,
          uuid: uuidv4(),
          privilege_name: "View Training",
          parent_id: 40000,
          is_parent: 0,
          is_menu: 0,
          is_action: 1,
          action_items: "1",
          sub_menu_name: "Manage Training",
          api_route: "",
          frontend_route: "/admin/dashboard/agent/view/:id",
        },
        {
          id: 40103,
          uuid: uuidv4(),
          privilege_name: "Edit Training",
          parent_id: 40000,
          is_parent: 0,
          is_menu: 0,
          is_action: 1,
          action_items: "0",
          sub_menu_name: "Manage Training",
          api_route: "",
          frontend_route: "/admin/dashboard/agent/modify/:id",
        },
        {
          id: 40104,
          uuid: uuidv4(),
          privilege_name: "Block/Unblock Training",
          parent_id: 40000,
          is_parent: 0,
          is_menu: 0,
          is_action: 1,
          action_items: "3",
          sub_menu_name: "Manage Training",
          api_route: "",
          frontend_route: "/admin/dashboard/agent/block-unblock",
        },
        {
          id: 50000,
          uuid: uuidv4(),
          privilege_name: "Certificate Management",
          parent_id: null,
          is_parent: 1,
          is_menu: 1,
          is_action: 0,
          action_items: "",
          sub_menu_name: "",
          api_route: "",
          frontend_route: "",
        },
        {
          id: 50100,
          uuid: uuidv4(),
          privilege_name: "Manage Certificate",
          parent_id: 50000,
          is_parent: 0,
          is_menu: 1,
          is_action: 0,
          action_items: "",
          sub_menu_name: "",
          api_route: "",
          frontend_route: "",
        },
        {
          id: 50101,
          uuid: uuidv4(),
          privilege_name: "Assign Certificates",
          parent_id: 50000,
          is_parent: 0,
          is_menu: 0,
          is_action: 1,
          action_items: "7",
          sub_menu_name: "Manage Certificate",
          api_route: "",
          frontend_route: "/admin/dashboard/certificate/manage",
        },
        {
          id: 50200,
          uuid: uuidv4(),
          privilege_name: "Generate Certificate",
          parent_id: 50000,
          is_parent: 0,
          is_menu: 1,
          is_action: 0,
          action_items: "",
          sub_menu_name: "",
          api_route: "",
          frontend_route: "",
        },
        {
          id: 50201,
          uuid: uuidv4(),
          privilege_name: "Get Certificate Detail",
          parent_id: 50000,
          is_parent: 0,
          is_menu: 0,
          is_action: 1,
          action_items: "7",
          sub_menu_name: "Generate Certificate",
          api_route: "",
          frontend_route: "/admin/dashboard/certificate/create",
        },
        {
          id: 60000,
          uuid: uuidv4(),
          privilege_name: "Reports",
          parent_id: null,
          is_parent: 1,
          is_menu: 1,
          is_action: 0,
          action_items: "",
          sub_menu_name: "",
          api_route: "",
          frontend_route: "",
        },
        {
          id: 60100,
          uuid: uuidv4(),
          privilege_name: "Participant Summary Report",
          parent_id: 60000,
          is_parent: 0,
          is_menu: 1,
          is_action: 0,
          action_items: "",
          sub_menu_name: "",
          api_route: "",
          frontend_route: "",
        },
        {
          id: 60200,
          uuid: uuidv4(),
          privilege_name: "Training Participant Report",
          parent_id: 60000,
          is_parent: 0,
          is_menu: 1,
          is_action: 0,
          action_items: "",
          sub_menu_name: "",
          api_route: "",
          frontend_route: "",
        },
        {
          id: 60300,
          uuid: uuidv4(),
          privilege_name: "Agent Report - Branch",
          parent_id: 60000,
          is_parent: 0,
          is_menu: 1,
          is_action: 0,
          action_items: "",
          sub_menu_name: "",
          api_route: "",
          frontend_route: "",
        },
        {
          id: 60400,
          uuid: uuidv4(),
          privilege_name: "Agent Report - Executive",
          parent_id: 60000,
          is_parent: 0,
          is_menu: 1,
          is_action: 0,
          action_items: "",
          sub_menu_name: "",
          api_route: "",
          frontend_route: "",
        },
        {
          id: 60500,
          uuid: uuidv4(),
          privilege_name: "Branch Wise Summary Report",
          parent_id: 60000,
          is_parent: 0,
          is_menu: 1,
          is_action: 0,
          action_items: "",
          sub_menu_name: "",
          api_route: "",
          frontend_route: "",
        },
        {
          id: 60600,
          uuid: uuidv4(),
          privilege_name: "Region Wise Summary Report",
          parent_id: 60000,
          is_parent: 0,
          is_menu: 1,
          is_action: 0,
          action_items: "",
          sub_menu_name: "",
          api_route: "",
          frontend_route: "",
        },
        {
          id: 60700,
          uuid: uuidv4(),
          privilege_name: "Attendance Report",
          parent_id: 60000,
          is_parent: 0,
          is_menu: 1,
          is_action: 0,
          action_items: "",
          sub_menu_name: "",
          api_route: "",
          frontend_route: "",
        },
        {
          id: 70000,
          uuid: uuidv4(),
          privilege_name: "Sms Management",
          parent_id: null,
          is_parent: 1,
          is_menu: 1,
          is_action: 0,
          action_items: "",
          sub_menu_name: "",
          api_route: "",
          frontend_route: "",
        },
        {
          id: 70100,
          uuid: uuidv4(),
          privilege_name: "Send Sms - Agent",
          parent_id: 70000,
          is_parent: 0,
          is_menu: 1,
          is_action: 0,
          action_items: "",
          sub_menu_name: "",
          api_route: "",
          frontend_route: "",
        },
        {
          id: 70200,
          uuid: uuidv4(),
          privilege_name: "Send Sms - Trainer",
          parent_id: 70000,
          is_parent: 0,
          is_menu: 1,
          is_action: 0,
          action_items: "",
          sub_menu_name: "",
          api_route: "",
          frontend_route: "",
        },
        {
          id: 80000,
          uuid: uuidv4(),
          privilege_name: "Attendance Management",
          parent_id: null,
          is_parent: 1,
          is_menu: 1,
          is_action: 0,
          action_items: "",
          sub_menu_name: "",
          api_route: "",
          frontend_route: "",
        },
        {
          id: 80100,
          uuid: uuidv4(),
          privilege_name: "Manage Attendance",
          parent_id: 80000,
          is_parent: 0,
          is_menu: 1,
          is_action: 0,
          action_items: "",
          sub_menu_name: "",
          api_route: "",
          frontend_route: "",
        },
        {
          id: 80101,
          uuid: uuidv4(),
          privilege_name: "Create Attendance",
          parent_id: 80000,
          is_parent: 0,
          is_menu: 0,
          is_action: 1,
          action_items: "7",
          sub_menu_name: "Attendance Management",
          api_route: "",
          frontend_route: "/admin/dashboard/agent/create",
        },
        {
          id: 80102,
          uuid: uuidv4(),
          privilege_name: "View Attendance",
          parent_id: 80000,
          is_parent: 0,
          is_menu: 0,
          is_action: 1,
          action_items: "1",
          sub_menu_name: "Attendance Management",
          api_route: "",
          frontend_route: "/admin/dashboard/agent/view/:id",
        },
        {
          id: 80103,
          uuid: uuidv4(),
          privilege_name: "Edit Attendance",
          parent_id: 80000,
          is_parent: 0,
          is_menu: 0,
          is_action: 1,
          action_items: "0",
          sub_menu_name: "Attendance Management",
          api_route: "",
          frontend_route: "/admin/dashboard/agent/modify/:id",
        },

      ]);
    } catch (error) {
      console.log(error)
      throw error
    }
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("menus", null,
      {}
    );
  }
};
